#! /usr/bin/bash
source tableScript

function createDB(){
	read -p "Enter the name of the database you want to create:" dbName
	
	if [ -d databases/${dbName} ]
	then
		echo That database name exists
	else
		mkdir "databases/${dbName}";
		echo Database ${dbName} Created
	fi
}

function listDBs(){
	ls -d "databases"/*/;
	
	echo Thats all the databases
}

connect_db(){
	read -p "Enter database name: " database
	
	if [ -d databases/${database} ]
	then 
		cd databases/${database}
		table_menu
		cd ../..
	else
		echo "Database name you entered does not exist"
	fi
}

drop_db(){
	read -p "Enter database name: " database
	
	if [ -d databases/${database} ]
	then 
		rm -r databases/${database}
		echo "Database Deleted"
	else
		echo "Database name you entered does not exist"
	fi
}

