#! /usr/bin/bash

source databaseScript
source tableScript

echo Main Menu:

declare -a options=("Create Database" "List Databases" "Connect To Databases" "Drop Database")

select option in "${options[@]}"
do
	case $option in 
		"Create Database")
			createDB
			;;
		"List Databases")
			listDBs
			;;
		"Connect To Databases")
			connect_db
			;;
		"Drop Database")
			drop_db
			;;
esac

done
