#! /usr/bin/bash

source databaseScript
source tableScript

echo Main Menu:

declare -a options=("Create Database" "List Databases" "Connect To Databases" "Drop Database")

select option in "${options[@]}"
do
	case $option in 
		"Create Database")
			read -p "Enter the name of the database you want to create:" dbName
			createDB "$dbName"
			echo Database $dbName Created
			;;
		"List Databases")
			listDBs
			echo Thats all the databases
			;;
		"Connect To Databases")
			#function call
			echo Database Connected
			;;
		"Drop Database")
			#function call
			echo Database dropped
			;;
esac

done
