#!/usr/bin/bash

table_menu(){
while true
do
	echo "Table Menu"
	echo "1) Create Table"
	echo "2) List Tables"
	echo "3) Drop Table"
	echo "4) Insert Into Table"
	echo "5) Select From Table"
	echo "6) Delete From Table"
	echo "7) Update Table"
	echo "8) Back"
	
	read -p "Enter your choice: " choice
	
	case $choice in
	1)
		create_table ;;
	2)
		list_tables ;;
	3)
		drop_table ;;
	4)
		insert_into_table ;;
	5)
		select_from_tables ;;
	6)
		delete_from_table ;;
	7)
		update_table ;;
	8)
		break ;;
	*)
		echo "Invalid choice" ;;
	esac
done
}

create_table(){
	read -p "Enter table name: " tname

	if [[ -z "$tname" || ! "$tname" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; 
	then
	    echo "Error: Invalid table name."
	    return
	fi
	

	if [ -f "$tname" ]; 
	then
	    echo "Error: Table '$tname' already exists."
	    return
	fi
	
	read -p "How many columns? " cols_num

	header=""
	pk_set=0

	for (( i=1; i<=cols_num; i++ )); 
	do
    	read -p "Column $i name: " cname
    	if [[ -z "$cname" || ! "$cname" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; 
    	then
        	echo "Invalid column name."; 
        	return
    	fi

    	while true; 
    	do
        	read -p "Datatype for '$cname' (int/string/float): " dtype
        	if [[ "$dtype" == "int" || "$dtype" == "string" || "$dtype" == "float" ]]; 
        	then
            		break
        	fi
        	echo "Invalid datatype. Choose: int, string, float"
    	done


    	pk_flag=""
    	if [ $pk_set -eq 0 ]; 
    	then
        	read -p "Is '$cname' the primary key? (y/n): " is_pk
        	if [[ "$is_pk" == "y" || "$is_pk" == "Y" ]]; 
        	then
            	pk_flag=":PK"
            	pk_set=1
        	fi
    	fi

        if [ -z "$header" ]; 
        then
        	header="$cname:$dtype$pk_flag"
    	else
        	header="$header|$cname:$dtype$pk_flag"
    	fi
    	
	done
	
	if [ $pk_set -eq 0 ]; 
	then
    	echo "Error: You must choose a primary key column."
    	echo "Table '$tname' was not created."
    	return
	fi
	
	
	touch $tname
	echo "$header" > "$tname"
	echo "Table '$tname' created successfully"

}

list_tables(){
	if [ "$(ls -A)" ]
	then
		ls -f 
		echo Thats all the tables
	else
		echo There is no saved tables
	fi
}

drop_table(){
	read -p "Enter table name: " tname
	
	if [ -f "$tname" ]
	then 
		rm $tname
		echo "Table Deleted"
	else
		echo "Error: Table name you entered does not exist"
	fi
}

insert_into_table(){
	read -p "Enter table name: " tname
	
        if [ -f "$tname" ];
        then
        	echo "That the '$tname' table :"
		cat "$tname"
		
		IFS='|' read -r -a columns < "$tname"
		new_row=""
		col_index=1
		
		for col_data in "${columns[@]}";
			do
			col_data=$(echo "$col_data" )
			col_name=$(echo "$col_data" | cut -d: -f1)
			col_type=$(echo "$col_data" | cut -d: -f2)
			col_pk=$(echo "$col_data" | cut -d: -f3 | xargs)
			
			valid=false
			while [ "$valid" = false ];
			do
				read -p "Enter $col_name ($col_type): " value
				
				if [ "$col_type" = "int" ];
				then
					if [[ ! $value =~ ^[0-9]+$ ]];
					then 
						echo "Invalid input! Please enter integer."
						continue
					fi
				elif [ "$col_type" = "float" ];
				then
					if [[ ! $value =~ ^[+-]?[0-9]*\.?[0-9]+$ ]];
					then
						echo "Invalid input! Please enter float."
						continue
					fi
				else
					valid=true
				fi
				
				if [ "$col_pk" = "PK" ]
				then
					if cut -d'|' -f"$col_index" "$tname" | tail -n +2 | grep -qx "$value"; 
					then
    						echo "This $col_name already exists, insert other $col_name"
						continue
					fi
				fi
				
				valid=true
			done
			
			if [ -z "$new_row" ];
			then
				new_row="$value"
			else
				new_row="$new_row|$value"
			fi
			((col_index ++))
		done
			
		echo "$new_row" >> "$tname"
		echo "Data inserted successfully"
        else
        	echo "There is no table with that name"
        fi
}

select_from_tables(){
	read -p "Enter table you want to select from:" tname
	
	if [ -f "$tname" ];
	then
		while true
		do
		
		echo "1) Select all from '$tname' "
		echo "2) Select with condition from '$tname' "
		echo "3) Back"
		
		read -p "Enter your choice: " choice
		
		case "$choice" in
			1)
				select_all;;
			2)
				select_with_condition;;
			3)
				break;;
			*)
			echo "Invalid choice" ;;
		esac
		done
	else 
		echo "Table '$tname' not found"
	fi
}

select_all(){
	if [ -f "$tname" ];
	then
		echo "================================================="
		echo "             Table '$tname'            "
		echo "================================================="
		column -t -s '|' "$tname"
		echo "================================================="
	else
		echo "Table not found"
	fi
}

select_with_condition(){
	read -p "Enter column name: " col_name
	read -p "Enter value: " value
	
	if [ -f "$tname" ];
	then
		header=$(head -1 "$tname")
		IFS='|' read -r -a columns <<< "$header"
		col_index=-1
		
		for i in "${!columns[@]}";
			do
			col=$(echo "${columns[$i]}" | cut -d':' -f1 | xargs)
			if [ "$col" == "$col_name" ];
			then
				col_index=$((i+1))
				break
			fi
		done

		if [ $col_index -eq -1 ];
		then
			echo "Column not found"
			return
		fi
		awk -F'|' -v col="$col_index" -v val="$value" '
			BEGIN {found=0}

			NR==1 {header=$0; next}

			$col == val {
			    if (found == 0) print header
			    print
			    found=1
			}

			END {
			    if (found == 0)
				print "No matching records found"
			}
			' "$tname" | column -t -s '|'
	else
		echo "Table not found"
	fi	
}

delete_from_table(){

	read -p "Enter table name: " tname

	if [ ! -f "$tname" ]; 
	then
    	echo "Table does not exist"
    	return
	fi

	header=$(head -1 "$tname")
	echo "Columns:"
	echo "$header" | tr '|' '\n' | cut -d':' -f1

	read -p "Enter column name: " col

	col_index=$(echo "$header" | tr '|' '\n' | grep -n "^$col:" | cut -d':' -f1)

	if [ -z "$col_index" ]; 
	then
    	echo "Column not found"
    	return
	fi

	read -p "Enter value to delete: " val

	found=$(awk -F'|' -v idx="$col_index" -v val="$val" '
	NR>1 && $idx==val {print; exit}
	' "$tname")

	if [ -z "$found" ]; 
	then
    	echo "Value not found. Nothing deleted."
    	return
	fi

	tmp=$(mktemp)

	awk -F'|' -v idx="$col_index" -v val="$val" '
	NR == 1 {print; next}
	$idx != val {print}
	' "$tname" > "$tmp"

	mv "$tmp" "$tname"
	echo "Delete completed"
}
